{{- if .Values.zipkin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "weatherspring.fullname" . }}-zipkin
  labels:
    {{- include "weatherspring.labels" . | nindent 4 }}
    app.kubernetes.io/component: tracing
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "weatherspring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: tracing
  template:
    metadata:
      labels:
        {{- include "weatherspring.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: tracing
    spec:
      containers:
      - name: zipkin
        image: "{{ .Values.zipkin.image.repository }}:{{ .Values.zipkin.image.tag }}"
        imagePullPolicy: {{ .Values.zipkin.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 9411
          protocol: TCP
        livenessProbe:
          {{- toYaml .Values.zipkin.probes.liveness | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.zipkin.probes.readiness | nindent 10 }}
        resources:
          {{- toYaml .Values.zipkin.resources | nindent 10 }}
        env:
        - name: JAVA_OPTS
          value: "-Xms128m -Xmx{{ .Values.zipkin.resources.limits.memory }}"
{{- end }}
