{{- if .Values.zipkin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "weatherspring.fullname" . }}-zipkin
  labels:
    {{- include "weatherspring.labels" . | nindent 4 }}
    app.kubernetes.io/component: tracing
spec:
  type: {{ .Values.zipkin.service.type }}
  ports:
  - port: {{ .Values.zipkin.service.port }}
    targetPort: 9411
    protocol: TCP
    name: http
    {{- if and (eq .Values.zipkin.service.type "NodePort") .Values.zipkin.service.nodePort }}
    nodePort: {{ .Values.zipkin.service.nodePort }}
    {{- end }}
  selector:
    {{- include "weatherspring.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: tracing
{{- end }}
